# This compose file is for development only
version: "3"
services:
  app:
    build: ./shipping
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./shipping:/src
    ports:
      - 8000:8000
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db

  db:
    image: mdillon/postgis
